version: "3.8"

services:
  # --- Backend API principal
  api_administracion:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: administracion-server-1
    image: administracion-server
    networks:
      - red-gane-int
    env_file:
      - ./server/.env

  # --- Proxy Nginx
  proxy_administracion:
    image: nginx:alpine
    container_name: proxy_administracion
    restart: unless-stopped
    networks:
      - red-gane-int
    expose:
      - "80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_administracion

networks:
  red-gane-int:
    external: true